my_solved/test/search.dart

test: branch test

---

my_solved/lib/veiws/search_view.dart

- 검색화면 검색결과 : 문제 제목 추가
-
-
-
-
- [v]  필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [v]  코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [v]  제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [v]  본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

fix : search_view

---

my_solved/lib/veiws/search_view.dart

- 검색화면 검색시 : users 이름과 tags 키값 추가
- 코파일럿의 힘을 빌려 카테고리 구분
-
- 한글 인코딩만 수정하면 검색 기능은 여기서 시마이쳐도 될듯 ㅋㅋㅋ
- 아 문제로 가는 링크가 있어야 겠네..
- [v]  필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [v]  코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [v]  제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [v]  본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

feat : add users & tags in search_view

---

my_solved/lib/veiws/search_view.dart

- 디자인은 구현했는데 아직 안넘어오는 값들이 많습니다,
- 모델에서 정확히 어떤거 써야할 지 모르겠,,.

검색 결과 UI 구현

---

my_solved/lib/models/User.dart
my_solved/lib/models/user/Background.dart
my_solved/lib/models/user/Organizations.dart
my_solved/lib/pages/profile_page.dart
my_solved/lib/providers/user/show_api.dart
my_solved/lib/view_models/main_tab_view_model.dart
my_solved/lib/view_models/profile_view_model.dart
my_solved/lib/views/profile_view.dart

feat : `profile_page`

---

my_solved/lib/pages/profile_detail_page.dart
my_solved/lib/view_models/profile_detail_view_model.dart
my_solved/lib/views/profile_detail_view.dart
my_solved/lib/views/search_view.dart

feat : profile_detail_view

---

my_solved/lib/views/home_view.dart
my_solved/lib/views/profile_detail_view.dart
my_solved/lib/widgets/user_widget.dart

feat : `home_view` & `profile_detail_view`

---

my_solved/lib/models/user/ProblemStats.dart
my_solved/lib/providers/user/problem_stats_api.dart
my_solved/lib/view_models/home_view_model.dart
my_solved/lib/views/home_view.dart
my_solved/lib/views/profile_detail_view.dart
my_solved/lib/widgets/user_widget.dart

refactor : `user_view`s

---

my_solved/ios/Podfile.lock
my_solved/lib/main.dart
my_solved/lib/pages/login_page.dart
my_solved/lib/view_models/login_view_model.dart
my_solved/lib/views/login_view.dart

- 로그인 화면 만들고, 메인화면하고 일단 연결 해놓음
-
-

feat: 로그인 화면 추가, 홈 화면과 연결

---

my_solved/lib/models/user/Top_100.dart
my_solved/lib/providers/user/top_100_api.dart

feat: top_100 api

---

.github/workflows/flutter.yaml

- 작업한 Flutter 프로젝트를 분석하는 CI를 추가했습니다.
- 없음

Add GitHub Actions configuration file for analyzing Flutter

---

.github/workflows/flutter.yaml

Fix problem that CI is failed

---

.github/workflows/flutter.yaml

- CI 동작에 오류가 추가로 발견되어 수정합니다.
- 없음

Fix problem that CI is failed, Part 2

---

my_solved/lib/models/badge.dart
my_solved/lib/models/user.dart
my_solved/lib/models/user/background.dart
my_solved/lib/models/user/organization.dart
my_solved/lib/models/user/organizations.dart
my_solved/lib/services/network_service.dart
my_solved/lib/views/home_view.dart
my_solved/lib/views/user_view.dart
my_solved/lib/widgets/user_widget.dart

Solvedac update

---

my_solved/ios/Podfile.lock
my_solved/ios/Runner/AppDelegate.swift
my_solved/lib/main.dart
my_solved/lib/services/notification_service.dart
my_solved/lib/services/user_service.dart
my_solved/lib/views/search_view.dart
my_solved/lib/views/setting_view.dart
my_solved/lib/widgets/user_widget.dart
my_solved/macos/Flutter/GeneratedPluginRegistrant.swift
my_solved/pubspec.yaml

- flutter_local_notification과 flutter_native_timezone, fullter_app_badger로 Local Notification을 구현했습니다.
- NotificationService를 통해 Notification 관련 기능들을 처리할 예정입니다.
- 스트릭 알림 기본 설정과 설정 방식을 수정했습니다(설정된 시간이 반영안되는 문제 수정)
- 많은 테스트를 하지 못해, 추가적인 테스트가 필요합니다.
- flutter_svg의 버전과 flutter_local_notification의 버전이 맞지 않은 문제가 발생해, flutter_svg 버전을 수정했습니다.
- 아이폰 내 Badge 관련 테스트가 필요합니다.
- 푸시 메시지를 임의로 넣었습니다.
- 안드로이드 테스트는 기기가 없어 불가능했습니다.

[FEAT] 스트릭 PUSH 알림 구현

---

my_solved/lib/views/contest_view.dart

- 라운드 UI v1 v2
- 어떤 게 더 나은 것 같음?
<table>
<th> v1 421b74f012ae66d66213aadcdbca2c30658923f2 </th>
<th> v2 </th>
<tr>
<td>     
</td>
<td>    
</td>
</tr>
</table>
-
-

feat: ContestView round UI v2

---

my_solved/android/app/src/main/AndroidManifest.xml
my_solved/lib/models/contest.dart
my_solved/lib/services/notification_service.dart
my_solved/lib/services/user_service.dart
my_solved/lib/views/contest_view.dart
my_solved/lib/views/setting_view.dart
my_solved/pubspec.yaml

- 대회 미리 알림 추가
<table>
<th> 대회 UI </th>
<th> 알림 </th>
<tr>
<td> 
</td>
<td>
</tr>
<th> 설정 UI </th>
<tr>
<td>
</td>
</tr>
</table>
-
-

Contest notification

---

my_solved/lib/services/network_service.dart
my_solved/pubspec.yaml

문제 검색창 `$me` 쿼리 지원

---

.gitignore
android/app/build.gradle
android/app/src/main/AndroidManifest.xml
ios/Podfile
ios/Runner.xcodeproj/project.pbxproj
ios/Runner/Info.plist
lib/features/contest/bloc/contest_bloc.dart
lib/features/contest/screen/contest_screen.dart
lib/features/home/screen/home_screen.dart
lib/features/setting/bloc/setting_bloc.dart
lib/features/setting/screen/setting_screen.dart
lib/main.dart
macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
pubspec.yaml

Closes #55 
Closes #56
Closes #57
- AOS & iOS 권한 설정 나랏이
- iOS 앱 키자마자 권한 설정 하던거 off
- 두 OS 동일하게 Permission Handler 라이브러리 사용하여 권한 예외처리 
- 스트릭 설정 버그 수정
- setting_screen에서 트롤 한거 있는데 수정함 
- 대회 진행바 구현
[Screen_recording_20240922_231832.webm](https://github.com/user-attachments/assets/9cd92849-6c5c-47dd-9160-101a53d7afea)
-
-

대회 진행바 추가, 권한 및 스트릭 설정 버그 수정

---

android/app/build.gradle
lib/features/home/screen/home_screen.dart
lib/features/login/bloc/login_bloc.dart
lib/features/login/screen/login_screen.dart
packages/apis/solved_api/lib/src/solved_api_client.dart
packages/apis/solved_api/pubspec.yaml
pubspec.yaml

- 웹에서 solved api 호출 대신 codepoker api 호출
- 뱃지 등록되지 않았을시 홈 화면 버그 수정
- 로그인시 존재하지 않는 아이디 버그 수정
-
-

웹, 로그인 개선 및 버그 수정

---

lib/features/root/screen/root_screen.dart
lib/features/search/bloc/search_bloc.dart
lib/features/search/bloc/search_event.dart
lib/features/search/bloc/search_state.dart
lib/features/search/screen/search_screen.dart
lib/features/search_filter/bloc/search_filter_state.dart
lib/features/search_filter/screen/search_filter_screen.dart
packages/repositories/shared_preferences_repository/lib/src/shared_preferences_repository.dart
pubspec.yaml

- Closes #65 
- Closes #66 
- Closes #67 
- Closes #68 
-
-

feat: search filter enhancement

---

ios/Podfile
ios/Runner.xcodeproj/project.pbxproj
ios/Runner/Info.plist
pubspec.yaml

[NON_ISSUE] Version 2.2.1 배포

---

ios/Podfile
ios/Runner.xcodeproj/project.pbxproj
lib/features/contest/bloc/contest_bloc.dart
lib/features/setting/bloc/setting_bloc.dart
pubspec.yaml

fix: notification permission
